version: '3'

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - db

  server:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./devops/broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./devops/broker/passwd:/mosquitto/passwd
  
  app:
    build:
      context: .
      dockerfile: devops/Dockerfile
    ports:
      - "8000:8000"
    
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - server
    volumes:
      - ./:/app
      
    restart: always

  celery:
    build: 
      context: .
      dockerfile: devops/Dockerfile
    command: celery -A config worker -l info
    volumes:
      - ./:/app

    depends_on:
      - db
      - redis
    links:
     - redis:redis
     - db

  celery-beat:
    build: 
      context: .
      dockerfile: devops/Dockerfile
    command: celery -A config beat -l info
    volumes:
      - ./:/app
      
    
    depends_on:
      - redis
    links:
     - redis:redis
     - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    
    depends_on:
      - app
    links:
      - app
    

volumes:

  db:
    driver: local
