# Generated by Django 4.0 on 2022-06-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='topic_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='topic_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
