# Generated by Django 4.0 on 2022-06-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_channel_topic_name_alter_sensor_topic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='channel',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='core.device'),
        ),
        migrations.AddField(
            model_name='smartcondition',
            name='channel',
            field=models.ManyToManyField(to='core.Channel'),
        ),
        migrations.AddField(
            model_name='smartcondition',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device'),
        ),
    ]
