# Generated by Django 4.0 on 2022-06-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_smartcondition_delete_status_alter_channel_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.device'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='core.device'),
        ),
    ]
