# Generated by Django 4.0 on 2022-06-29 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_channel_device_alter_sensor_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcondition',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.device'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SensorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('above', models.CharField(max_length=200)),
                ('below', models.CharField(max_length=200)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.CharField(blank=True, max_length=200, null=True)),
                ('sensor_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sensorstate')),
            ],
        ),
    ]
