# Generated by Django 4.0 on 2022-06-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_smartcondition_device_sensorstate_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorstate',
            name='sensor',
        ),
        migrations.AlterField(
            model_name='condition',
            name='timer',
            field=models.DateField(blank=True, null=True),
        ),
    ]
