# Generated by Django 4.0 on 2022-06-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_condition_sensor_status_delete_sensorstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('above', models.CharField(max_length=200)),
                ('below', models.CharField(max_length=200)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='sensor_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sensorstate'),
        ),
    ]
