# Generated by Django 4.0 on 2022-06-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sensorstate_condition_sensor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcondition',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.condition'),
            preserve_default=False,
        ),
    ]
