# Generated by Django 4.0 on 2022-06-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_smartcondition_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='timer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
