# Generated by Django 4.0.6 on 2022-07-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_smartcondition_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
