# Generated by Django 4.0.6 on 2022-07-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_channel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorstate',
            name='above',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sensorstate',
            name='below',
            field=models.IntegerField(max_length=200),
        ),
    ]
