# Generated by Django 4.0.6 on 2022-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sensorstate_above_alter_sensorstate_below'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorstate',
            name='above',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorstate',
            name='below',
            field=models.IntegerField(),
        ),
    ]
