# Generated by Django 4.0.6 on 2022-07-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_sensorstate_above_alter_sensorstate_below'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='timer',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
