# Generated by Django 4.0.6 on 2022-07-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_smartcondition_created_at_smartcondition_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_home', to='core.home'),
        ),
    ]
