# Generated by Django 4.0.6 on 2022-07-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_device_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcondition',
            name='status',
            field=models.CharField(max_length=3),
        ),
    ]
